production:
    connection:
        url: http://localhost o http://IPMàquinaVirual # Canvia això per la ip de la màquina virtual o localhost si ho fas en la màquina virtual
        port: 8069 # Canvia això si tens un port diferent
        db: nom_db # Canvia això pel nom de la base de dades
        user: odoo@odoo.com # Canvia això pel correu que tingues en el correu
        password: **********47d1e3ac55********** # Canvia això per l'API que et genera Odoo

development:
    connection:
        url: http://localhost o http://IPMàquinaVirual # Canvia això per la ip de la màquina virtual o localhost si ho fas en la màquina virtual
        port: 8069 # Canvia això si tens un port diferent
        db: nom_db # Canvia això pel nom de la base de dades
        user: odoo@odoo.com # Canvia això pel correu que tingues en el correu
        password: **********47d1e3ac55********** # Canvia això per l'API que et genera Odoo
