production:    
    connection:
        url: http://192.168.152.26:8069
        port: 8069
        db: Projecte_Falla
        user: Administrator
        password: "cc8f01eee7cd89228224386fc74a6ff0f2228408"

development:    
    connection:
        url: http://192.168.152.26:8069
        port: 8069
        db: Projecte_Falla
        user: Administrator
        password: "cc8f01eee7cd89228224386fc74a6ff0f2228408"